<?php
/**
 * @var \Phalcon\Mvc\View\Engine\Php $this
 */
?>

<div class="page-header">
    <h1>
        Pergunta
    </h1>
    <p>
        <?php echo $this->tag->linkTo(array("pergunta/new", "Criar pergunta")) ?>
    </p>
</div>

<?php echo $this->getContent() ?>

<?php
    echo $this->tag->form(
        array(
            "pergunta/search",
            "autocomplete" => "off",
            "class" => "form-horizontal"
        )
    );
?>

<div class="form-group">
    <label for="fieldCategoriacodcat" class="col-sm-2 control-label">Código da categoria </label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(array("categoriacodcat", "type" => "number", "class" => "form-control", "id" => "fieldCategoriacodcat")) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldCodper" class="col-sm-2 control-label">Código da perguta </label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(array("codper", "type" => "number", "class" => "form-control", "id" => "fieldCodper")) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldDesper" class="col-sm-2 control-label">Descrição pergunta </label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(array("desper", "size" => 30, "class" => "form-control", "id" => "fieldDesper")) ?>
    </div>
</div>


<div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
        <?php echo $this->tag->submitButton(array("Pesquisar", "class" => "btn btn-default")) ?>
    </div>
</div>

<?php echo $this->tag->endForm(); ?>
