<?php
/**
 * @var \Phalcon\Mvc\View\Engine\Php $this
 */
?>

<div class="row">
    <nav>
        <ul class="pager">
            <li class="previous"><?php echo $this->tag->linkTo(array("pergunta", "Voltar")) ?></li>
        </ul>
    </nav>
</div>

<div class="page-header">
    <h1>
        Criar pergunta
    </h1>
</div>

<?php echo $this->getContent(); ?>

<?php
    echo $this->tag->form(
        array(
            "pergunta/create",
            "autocomplete" => "off",
            "class" => "form-horizontal"
        )
    );
?>

<div class="form-group">
    <label for="fieldCategoriacodcat" class="col-sm-2 control-label">Código da pergunta </label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(array("categoriacodcat", "type" => "number", "class" => "form-control", "id" => "fieldCategoriacodcat")) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldDesper" class="col-sm-2 control-label">Descrição da pergunta </label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(array("desper", "size" => 30, "class" => "form-control", "id" => "fieldDesper")) ?>
    </div>
</div>


<div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
        <?php echo $this->tag->submitButton(array("Salvar", "class" => "btn btn-default")) ?>
    </div>
</div>

<?php echo $this->tag->endForm(); ?>
