<?php
/**
 * @var \Phalcon\Mvc\View\Engine\Php $this
 */
?>

<div class="page-header">
    <h1>
        Search opcao
    </h1>
    <p>
        <?php echo $this->tag->linkTo(["opcao/new", "Create opcao"]) ?>
    </p>
</div>

<?php echo $this->getContent() ?>

<?php
    echo $this->tag->form(
        [
            "opcao/search",
            "autocomplete" => "off",
            "class" => "form-horizontal"
        ]
    );
?>

<div class="form-group">
    <label for="fieldPerguntacodper" class="col-sm-2 control-label">Perguntacodper</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(["perguntacodper", "type" => "number", "class" => "form-control", "id" => "fieldPerguntacodper"]) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldCodopc" class="col-sm-2 control-label">Codopc</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(["codopc", "type" => "number", "class" => "form-control", "id" => "fieldCodopc"]) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldDesopc" class="col-sm-2 control-label">Desopc</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(["desopc", "size" => 30, "class" => "form-control", "id" => "fieldDesopc"]) ?>
    </div>
</div>


<div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
        <?php echo $this->tag->submitButton(["Search", "class" => "btn btn-default"]) ?>
    </div>
</div>

<?php echo $this->tag->endForm(); ?>
