<?php
/**
 * @var \Phalcon\Mvc\View\Engine\Php $this
 */
?>

<div class="row">
    <nav>
        <ul class="pager">
            <li class="previous"><?php echo $this->tag->linkTo(["opcao", "Go Back"]) ?></li>
        </ul>
    </nav>
</div>

<div class="page-header">
    <h1>
        Create opcao
    </h1>
</div>

<?php echo $this->getContent(); ?>

<?php
    echo $this->tag->form(
        [
            "opcao/create",
            "autocomplete" => "off",
            "class" => "form-horizontal"
        ]
    );
?>

<div class="form-group">
    <label for="fieldPerguntacodper" class="col-sm-2 control-label">Perguntacodper</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(["perguntacodper", "type" => "number", "class" => "form-control", "id" => "fieldPerguntacodper"]) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldDesopc" class="col-sm-2 control-label">Desopc</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(["desopc", "size" => 30, "class" => "form-control", "id" => "fieldDesopc"]) ?>
    </div>
</div>


<div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
        <?php echo $this->tag->submitButton(["Save", "class" => "btn btn-default"]) ?>
    </div>
</div>

<?php echo $this->tag->endForm(); ?>
