<?php
/**
 * @var \Phalcon\Mvc\View\Engine\Php $this
 */
?>

<div class="page-header">
    <h1>
        Pessoa
    </h1>
    <p>
        <?php echo $this->tag->linkTo(array("pessoa/new", "Criar pessoa")) ?>
    </p>
</div>

<?php echo $this->getContent() ?>

<?php
    echo $this->tag->form(
        array(
            "pessoa/search",
            "autocomplete" => "off",
            "class" => "form-horizontal"
        )
    );
?>

<div class="form-group">
    <label for="fieldCodpes" class="col-sm-2 control-label">Código:</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(array("codpes", "type" => "number", "class" => "form-control", "id" => "fieldCodpes")) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldNompes" class="col-sm-2 control-label">Nome:</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(array("nompes", "size" => 30, "class" => "form-control", "id" => "fieldNompes")) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldFotpes" class="col-sm-2 control-label">Foto</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(array("fotpes", "size" => 30, "class" => "form-control", "id" => "fieldFotpes")) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldCpfpes" class="col-sm-2 control-label">Cpf:</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(array("cpfpes", "size" => 30, "class" => "form-control", "id" => "fieldCpfpes")) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldAlunocodMatricula" class="col-sm-2 control-label">Código de matricula:</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(array("alunocod_matricula", "type" => "number", "class" => "form-control", "id" => "fieldAlunocodMatricula")) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldDasnascpes" class="col-sm-2 control-label">Data de nascimento:</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(array("dasnascpes", "type" => "date", "class" => "form-control", "id" => "fieldDasnascpes")) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldEmapes" class="col-sm-2 control-label">Email</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(array("emapes", "size" => 30, "class" => "form-control", "id" => "fieldEmapes")) ?>
    </div>
</div>


<div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
        <?php echo $this->tag->submitButton(array("Pesquisar", "class" => "btn btn-default")) ?>
    </div>
</div>

<?php echo $this->tag->endForm(); ?>
