<?php
/**
 * @var \Phalcon\Mvc\View\Engine\Php $this
 */
?>

<?php use Phalcon\Tag; ?>

<div class="row">
    <nav>
        <ul class="pager">
            <li class="previous"><?php echo $this->tag->linkTo(array("pessoa/index", "Go Back")); ?></li>
            <li class="next"><?php echo $this->tag->linkTo(array("pessoa/new", "Create ")); ?></li>
        </ul>
    </nav>
</div>

<div class="page-header">
    <h1>Search result</h1>
</div>

<?php echo $this->getContent(); ?>

<div class="row">
    <table class="table table-bordered">
        <thead>
            <tr>
                <th>Codpes</th>
            <th>Nompes</th>
            <th>Fotpes</th>
            <th>Cpfpes</th>
            <th>Alunocod Of Matricula</th>
            <th>Dasnascpes</th>
            <th>Emapes</th>

                <th></th>
                <th></th>
            </tr>
        </thead>
        <tbody>
        <?php foreach ($page->items as $pessoa): ?>
            <tr>
                <td><?php echo $pessoa->codpes ?></td>
            <td><?php echo $pessoa->nompes ?></td>
            <td><?php echo $pessoa->fotpes ?></td>
            <td><?php echo $pessoa->cpfpes ?></td>
            <td><?php echo $pessoa->alunocod_matricula ?></td>
            <td><?php echo $pessoa->dasnascpes ?></td>
            <td><?php echo $pessoa->emapes ?></td>

                <td><?php echo $this->tag->linkTo(array("pessoa/edit/" . $pessoa->codpes, "Edit")); ?></td>
                <td><?php echo $this->tag->linkTo(array("pessoa/delete/" . $pessoa->codpes, "Delete")); ?></td>
            </tr>
        <?php endforeach; ?>
        </tbody>
    </table>
</div>

<div class="row">
    <div class="col-sm-1">
        <p class="pagination" style="line-height: 1.42857;padding: 6px 12px;">
            <?php echo $page->current, "/", $page->total_pages ?>
        </p>
    </div>
    <div class="col-sm-11">
        <nav>
            <ul class="pagination">
                <li><?php echo $this->tag->linkTo("pessoa/search", "First") ?></li>
                <li><?php echo $this->tag->linkTo("pessoa/search?page=" . $page->before, "Previous") ?></li>
                <li><?php echo $this->tag->linkTo("pessoa/search?page=" . $page->next, "Next") ?></li>
                <li><?php echo $this->tag->linkTo("pessoa/search?page=" . $page->last, "Last") ?></li>
            </ul>
        </nav>
    </div>
</div>
