<?php
/**
 * @var \Phalcon\Mvc\View\Engine\Php $this
 */
?>

<div class="page-header">
    <h1>
        Search turma_aluno
    </h1>
    <p>
        <?php echo $this->tag->linkTo(array("turma_aluno/new", "Create turma_aluno")) ?>
    </p>
</div>

<?php echo $this->getContent() ?>

<?php
    echo $this->tag->form(
        array(
            "turma_aluno/search",
            "autocomplete" => "off",
            "class" => "form-horizontal"
        )
    );
?>

<div class="form-group">
    <label for="fieldTurmacodtur" class="col-sm-2 control-label">Turmacodtur</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(array("turmacodtur", "type" => "number", "class" => "form-control", "id" => "fieldTurmacodtur")) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldAlunocodMatricula" class="col-sm-2 control-label">Alunocod Of Matricula</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(array("alunocod_matricula", "type" => "number", "class" => "form-control", "id" => "fieldAlunocodMatricula")) ?>
    </div>
</div>


<div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
        <?php echo $this->tag->submitButton(array("Search", "class" => "btn btn-default")) ?>
    </div>
</div>

<?php echo $this->tag->endForm(); ?>
