<?php
/**
 * @var \Phalcon\Mvc\View\Engine\Php $this
 */
?>

<div class="page-header">
    <h1>
        Peer respostas
    </h1>
    <p>
        <?php echo $this->tag->linkTo(array("peerrespostas/new", "Criar peer respostas")) ?>
    </p>
</div>

<?php echo $this->getContent() ?>

<?php
    echo $this->tag->form(
        array(
            "peerrespostas/search",
            "autocomplete" => "off",
            "class" => "form-horizontal"
        )
    );
?>

<div class="form-group">
    <label for="fieldAlunocodMatricula" class="col-sm-2 control-label">Código da matricula do Aluno</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(array("alunocod_matricula", "type" => "number", "class" => "form-control", "id" => "fieldAlunocodMatricula")) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldOpcaocodopc" class="col-sm-2 control-label">Código da opção </label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(array("opcaocodopc", "type" => "number", "class" => "form-control", "id" => "fieldOpcaocodopc")) ?>
    </div>
</div>


<div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
        <?php echo $this->tag->submitButton(array("Pesquisar", "class" => "btn btn-default")) ?>
    </div>
</div>

<?php echo $this->tag->endForm(); ?>
