<?php
/**
 * @var \Phalcon\Mvc\View\Engine\Php $this
 */
?>

<div class="row">
    <nav>
        <ul class="pager">
            <li class="previous"><?php echo $this->tag->linkTo(array("professor", "Voltar")) ?></li>
        </ul>
    </nav>
</div>

<div class="page-header">
    <h1>
        Editar professor
    </h1>
</div>

<?php echo $this->getContent(); ?>

<?php
    echo $this->tag->form(
        array(
            "professor/save",
            "autocomplete" => "off",
            "class" => "form-horizontal"
        )
    );
?>

<div class="form-group">
    <label for="fieldCodprofessor" class="col-sm-2 control-label">Código do Professor</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(array("codprofessor", "type" => "number", "class" => "form-control", "id" => "fieldCodprofessor")) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldDespro" class="col-sm-2 control-label">Nome</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(array("despro", "size" => 30, "class" => "form-control", "id" => "fieldDespro")) ?>
    </div>
</div>


<?php echo $this->tag->hiddenField("id") ?>

<div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
        <?php echo $this->tag->submitButton(array("Salvar", "class" => "btn btn-default")) ?>
    </div>
</div>

<?php echo $this->tag->endForm(); ?>
