<?php
/**
 * @var \Phalcon\Mvc\View\Engine\Php $this
 */
?>

<div class="page-header">
    <h1>
        Search professor
    </h1>
    <p>
        <?php echo $this->tag->linkTo(array("professor/new", "Create professor")) ?>
    </p>
</div>

<?php echo $this->getContent() ?>

<?php
    echo $this->tag->form(
        array(
            "professor/search",
            "autocomplete" => "off",
            "class" => "form-horizontal"
        )
    );
?>

<div class="form-group">
    <label for="fieldCodprofessor" class="col-sm-2 control-label">Codprofessor</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(array("codprofessor", "type" => "number", "class" => "form-control", "id" => "fieldCodprofessor")) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldDespro" class="col-sm-2 control-label">Despro</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(array("despro", "size" => 30, "class" => "form-control", "id" => "fieldDespro")) ?>
    </div>
</div>


<div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
        <?php echo $this->tag->submitButton(array("Search", "class" => "btn btn-default")) ?>
    </div>
</div>

<?php echo $this->tag->endForm(); ?>
