<?php
/**
 * @var \Phalcon\Mvc\View\Engine\Php $this
 */
?>

<div class="page-header">
    <h1>
        Peer Aluno
    </h1>
    <p>
        <?php echo $this->tag->linkTo(array("peer_aluno/new", "Criar Peer aluno")) ?>
    </p>
</div>

<?php echo $this->getContent() ?>

<?php
    echo $this->tag->form(
        array(
            "peer_aluno/search",
            "autocomplete" => "off",
            "class" => "form-horizontal"
        )
    );
?>

<div class="form-group">
    <label for="fieldPeercodpee" class="col-sm-2 control-label">Código do peer </label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(array("peercodpee", "type" => "number", "class" => "form-control", "id" => "fieldPeercodpee")) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldAlunocodMatricula" class="col-sm-2 control-label">Código da matricula do aluno </label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(array("alunocod_matricula", "type" => "number", "class" => "form-control", "id" => "fieldAlunocodMatricula")) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldDatexecpeer" class="col-sm-2 control-label">Data de execução do peer </label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(array("datexecpeer", "type" => "date", "class" => "form-control", "id" => "fieldDatexecpeer")) ?>
    </div>
</div>


<div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
        <?php echo $this->tag->submitButton(array("Procurar", "class" => "btn btn-default")) ?>
    </div>
</div>

<?php echo $this->tag->endForm(); ?>
