<?php
/**
 * @var \Phalcon\Mvc\View\Engine\Php $this
 */
?>

<?php use Phalcon\Tag; ?>

<div class="row">
    <nav>
        <ul class="pager">
            <li class="previous"><?php echo $this->tag->linkTo(array("peer_aluno/index", "Voltar")); ?></li>
            <li class="next"><?php echo $this->tag->linkTo(array("peer_aluno/new", "Criar ")); ?></li>
        </ul>
    </nav>
</div>

<div class="page-header">
    <h1>Procurar Resultados </h1>
</div>

<?php echo $this->getContent(); ?>

<div class="row">
    <table class="table table-bordered">
        <thead>
            <tr>
                <th>Peercodpee</th>
            <th>Alunocod Of Matricula</th>
            <th>Datexecpeer</th>

                <th></th>
                <th></th>
            </tr>
        </thead>
        <tbody>
        <?php foreach ($page->items as $peer_aluno): ?>
            <tr>
                <td><?php echo $peer_aluno->peercodpee ?></td>
            <td><?php echo $peer_aluno->alunocod_matricula ?></td>
            <td><?php echo $peer_aluno->datexecpeer ?></td>

                <td><?php echo $this->tag->linkTo(array("peer_aluno/edit/" . $peer_aluno->peercodpee, "Edit")); ?></td>
                <td><?php echo $this->tag->linkTo(array("peer_aluno/delete/" . $peer_aluno->peercodpee, "Delete")); ?></td>
            </tr>
        <?php endforeach; ?>
        </tbody>
    </table>
</div>

<div class="row">
    <div class="col-sm-1">
        <p class="pagination" style="line-height: 1.42857;padding: 6px 12px;">
            <?php echo $page->current, "/", $page->total_pages ?>
        </p>
    </div>
    <div class="col-sm-11">
        <nav>
            <ul class="pagination">
                <li><?php echo $this->tag->linkTo("peer_aluno/search", "First") ?></li>
                <li><?php echo $this->tag->linkTo("peer_aluno/search?page=" . $page->before, "Previous") ?></li>
                <li><?php echo $this->tag->linkTo("peer_aluno/search?page=" . $page->next, "Next") ?></li>
                <li><?php echo $this->tag->linkTo("peer_aluno/search?page=" . $page->last, "Last") ?></li>
            </ul>
        </nav>
    </div>
</div>
