<?php
/**
 * @var \Phalcon\Mvc\View\Engine\Php $this
 */
?>

<?php use Phalcon\Tag; ?>

<div class="row">
    <nav>
        <ul class="pager">
            <li class="previous"><?php echo $this->tag->linkTo(array("peer/index", "Voltar")); ?></li>
            <li class="next"><?php echo $this->tag->linkTo(array("peer/new", "Criar ")); ?></li>
        </ul>
    </nav>
</div>

<div class="page-header">
    <h1>Relatorios dos Peer </h1>
</div>

<?php echo $this->getContent(); ?>

<div class="row">
    <table class="table table-bordered">
        <thead>
            <tr>
                <th>Código da turma</th>
            <th>Código do peer</th>
            <th>Descrição do peer</th>
            <th>Data de cadastro do peer</th>
            <th>Data da execução</th>
            <th>Data final</th>

                <th></th>
                <th></th>
            </tr>
        </thead>
        <tbody>
        <?php foreach ($page->items as $peer): ?>
            <tr>
                <td><?php echo $peer->turmacodtur ?></td>
            <td><?php echo $peer->codpee ?></td>
            <td><?php echo $peer->despee ?></td>
            <td><?php echo $peer->datcadpee ?></td>
            <td><?php echo $peer->dasexepee ?></td>
            <td><?php echo $peer->dasfimpee ?></td>

                <td><?php echo $this->tag->linkTo(array("peer/edit/" . $peer->turmacodtur, "Editar")); ?></td>
                <td><?php echo $this->tag->linkTo(array("peer/delete/" . $peer->turmacodtur, "Deletar")); ?></td>
            </tr>
        <?php endforeach; ?>
        </tbody>
    </table>
</div>

<div class="row">
    <div class="col-sm-1">
        <p class="pagination" style="line-height: 1.42857;padding: 6px 12px;">
            <?php echo $page->current, "/", $page->total_pages ?>
        </p>
    </div>
    <div class="col-sm-11">
        <nav>
            <ul class="pagination">
                <li><?php echo $this->tag->linkTo("peer/search", "Primeiro") ?></li>
                <li><?php echo $this->tag->linkTo("peer/search?page=" . $page->before, "Anterior") ?></li>
                <li><?php echo $this->tag->linkTo("peer/search?page=" . $page->next, "Proximo") ?></li>
                <li><?php echo $this->tag->linkTo("peer/search?page=" . $page->last, "Final") ?></li>
            </ul>
        </nav>
    </div>
</div>
