<?php
/**
 * @var \Phalcon\Mvc\View\Engine\Php $this
 */
?>

<div class="page-header">
    <h1>
        Perguntas do peer!
    </h1>
</div>
<?php echo $this->getContent(); ?> 
<?php
echo $this->tag->form(
        array(
            "peeraluno/create",
            "autocomplete" => "off",
            "class" => "form-horizontal"
        )
);
$i = 1;
foreach ($perguntas as $pergunta) {

    echo  "<h3>" . $pergunta->desper . "</h3>". "<br/>";
    foreach ($pergunta->opcoes as $opcao) {
        echo Phalcon\Tag::radioField(
                ["per[$pergunta->codper]",
                    "value" => $opcao->codopc,
        ]);
        
        echo "\t" . $opcao->desopc ;
                echo("<br/>");
                
    }
    $i++;
    echo ("<hr>");
      echo("<br/><br/>");
  
}

?>

<div class="form-group">
  <div class="col-sm-offset-2 col-sm-10">
     <?php echo $this->tag->submitButton(array("Responder", "class" => "btn btn-default")) ?>
    </div>
</div>
<?php echo $this->tag->endForm(); ?>
