<?php
/**
 * @var \Phalcon\Mvc\View\Engine\Php $this
 */
?>

<div class="page-header">
    <h1>
        Categoria
    </h1>
    <p>
        <?php echo $this->tag->linkTo(array("categoria/new", "Criar categoria")) ?>
    </p>
</div>

<?php echo $this->getContent() ?>

<?php
    echo $this->tag->form(
        array(
            "categoria/search",
            "autocomplete" => "off",
            "class" => "form-horizontal"
        )
    );
?>

<div class="form-group">
    <label for="fieldCodcat" class="col-sm-2 control-label">Código da categoria </label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(array("codcat", "type" => "number", "class" => "form-control", "id" => "fieldCodcat")) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldDescat" class="col-sm-2 control-label">Descrição da categoria </label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(array("descat", "size" => 30, "class" => "form-control", "id" => "fieldDescat")) ?>
    </div>
</div>


<div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
        <?php echo $this->tag->submitButton(array("Procurar", "class" => "btn btn-default")) ?>
    </div>
</div>

<?php echo $this->tag->endForm(); ?>
