<?php
/**
 * @var \Phalcon\Mvc\View\Engine\Php $this
 */
?>

<div class="row">
    <nav>
        <ul class="pager">
            <li class="previous"><?php echo $this->tag->linkTo(array("aluno", "Voltar")) ?></li>
        </ul>
    </nav>
</div>

<div class="page-header">
    <h1>
        Editar Aluno
    </h1>
</div>

<?php echo $this->getContent(); ?>

<?php
    echo $this->tag->form(
        array(
            "aluno/save",
            "autocomplete" => "off",
            "class" => "form-horizontal"
        )
    );
?>

<div class="form-group">
    <label for="fieldDesalu" class="col-sm-2 control-label">Descrição Aluno </label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(array("desalu", "size" => 30, "class" => "form-control", "id" => "fieldDesalu")) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldDascadalu" class="col-sm-2 control-label">Data de cadastro do aluno </label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(array("dascadalu", "type" => "date", "class" => "form-control", "id" => "fieldDascadalu")) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldSitalu" class="col-sm-2 control-label">Situação do Aluno </label>
    <div class="col-sm-10">
        <?php echo $this->tag->selectStatic(array("sitalu", array(), "class" => "form-control", "id" => "fieldSitalu")) ?>
    </div>
</div>


<?php echo $this->tag->hiddenField("id") ?>

<div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
        <?php echo $this->tag->submitButton(array("Salvar", "class" => "btn btn-default")) ?>
    </div>
</div>

<?php echo $this->tag->endForm(); ?>
