<?php
/**
 * @var \Phalcon\Mvc\View\Engine\Php $this
 */
?>

<div class="page-header">
    <h1>
        Aluno
    </h1>
    <p>
        <?php echo $this->tag->linkTo(array("aluno/new", "Criar Aluno")) ?>
    </p>
</div>

<?php echo $this->getContent() ?>

<?php
    echo $this->tag->form(
        array(
            "aluno/search",
            "autocomplete" => "off",
            "class" => "form-horizontal"
        )
    );
?>

<div class="form-group">
    <label for="fieldCodmat" class="col-sm-2 control-label">Códido da matricula: </label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(array("codmat", "type" => "number", "class" => "form-control", "id" => "fieldCodmat")) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldDesalu" class="col-sm-2 control-label">Nome: </label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(array("desalu", "size" => 30, "class" => "form-control", "id" => "fieldDesalu")) ?>
    </div>
</div>


<div class="form-group">
    <label for="fieldSitalu" class="col-sm-2 control-label">Situação aluno: </label>
    <div class="col-sm-10">
        <?php echo $this->tag->selectStatic(array("sitalu", array("Ativo" , "Inativo"), "class" => "form-control", "id" => "fieldSitalu")) ?>
    </div>
</div>


<div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
        <?php echo $this->tag->submitButton(array("Pesquisar", "class" => "btn btn-default")) ?>
    </div>
</div>

<?php echo $this->tag->endForm(); ?>
