<?php
/**
 * @var \Phalcon\Mvc\View\Engine\Php $this
 */
?>

<?php use Phalcon\Tag; ?>

<div class="row">
    <nav>
        <ul class="pager">
            <li class="previous"><?php echo $this->tag->linkTo(array("aluno/index", "Voltar")); ?></li>
            <li class="next"><?php echo $this->tag->linkTo(array("aluno/new", "Criar ")); ?></li>
        </ul>
    </nav>
</div>

<div class="page-header">
    <h1>Procurar resultados </h1>
</div>

<?php echo $this->getContent(); ?>

<div class="row">
    <table class="table table-bordered">
        <thead>
            <tr>
                <th>Codmat</th>
            <th>Desalu</th>
            <th>Dascadalu</th>
            <th>Sitalu</th>

                <th></th>
                <th></th>
            </tr>
        </thead>
        <tbody>
        <?php foreach ($page->items as $aluno): ?>
            <tr>
                <td><?php echo $aluno->codmat ?></td>
            <td><?php echo $aluno->desalu ?></td>
            <td><?php echo $aluno->dascadalu ?></td>
            <td><?php echo $aluno->sitalu ?></td>

                <td><?php echo $this->tag->linkTo(array("aluno/edit/" . $aluno->codmat, "Edit")); ?></td>
                <td><?php echo $this->tag->linkTo(array("aluno/delete/" . $aluno->codmat, "Delete")); ?></td>
            </tr>
        <?php endforeach; ?>
        </tbody>
    </table>
</div>

<div class="row">
    <div class="col-sm-1">
        <p class="pagination" style="line-height: 1.42857;padding: 6px 12px;">
            <?php echo $page->current, "/", $page->total_pages ?>
        </p>
    </div>
    <div class="col-sm-11">
        <nav>
            <ul class="pagination">
                <li><?php echo $this->tag->linkTo("aluno/search", "First") ?></li>
                <li><?php echo $this->tag->linkTo("aluno/search?page=" . $page->before, "Previous") ?></li>
                <li><?php echo $this->tag->linkTo("aluno/search?page=" . $page->next, "Next") ?></li>
                <li><?php echo $this->tag->linkTo("aluno/search?page=" . $page->last, "Last") ?></li>
            </ul>
        </nav>
    </div>
</div>
