<?php
/**
 * @var \Phalcon\Mvc\View\Engine\Php $this
 */

?>
<?php use Phalcon\Tag; ?>
<div class="page-header">
    <h1>
        Relatorios dos peers respondidos!
    </h1>
<?php echo $this->getContent(); ?>

<div class="row">
    <table class="table table-bordered">
        <thead>
            <tr>
             <th>Descrição do peer</th>
        <th></th>
            </tr>
        </thead>
        <tbody>
        <?php foreach ($page->items as $peer): ?>
            <tr>
                <td><?php echo $peer->despee ?></td>
                <td><?php echo $this->tag->linkTo(array("peerrelatorios/" . $peer->codpee, "Relatório")); ?></td>
            </tr>
        <?php endforeach; ?>
        </tbody>
    </table>
