<?php
/**
 * @var \Phalcon\Mvc\View\Engine\Php $this
 */
?>

<div class="row">
    <nav>
        <ul class="pager">
            <li class="previous"><?php echo $this->tag->linkTo(array("turma", "Voltar")) ?></li>
        </ul>
    </nav>
</div>

<div class="page-header">
    <h1>
        Editar turma
    </h1>
</div>

<?php echo $this->getContent(); ?>

<?php
    echo $this->tag->form(
        array(
            "turma/save",
            "autocomplete" => "off",
            "class" => "form-horizontal"
        )
    );
?>

<div class="form-group">
    <label for="fieldAlunocodMatricula" class="col-sm-2 control-label">Coódigo de matricula do aluno:</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(array("alunocod_matricula", "type" => "number", "class" => "form-control", "id" => "fieldAlunocodMatricula")) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldProfesorpessoacodigo" class="col-sm-2 control-label">Código do professor:</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(array("profesorpessoacodigo", "type" => "number", "class" => "form-control", "id" => "fieldProfesorpessoacodigo")) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldDestur" class="col-sm-2 control-label">Nome Turma:</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(array("destur", "size" => 30, "class" => "form-control", "id" => "fieldDestur")) ?>
    </div>
</div>


<?php echo $this->tag->hiddenField("id") ?>

<div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
        <?php echo $this->tag->submitButton(array("Salvar", "class" => "btn btn-default")) ?>
    </div>
</div>

<?php echo $this->tag->endForm(); ?>
