<?php
/**
 * @var \Phalcon\Mvc\View\Engine\Php $this
 */
?>

<div class="page-header">
    <h1>
        Pesquisar turma
    </h1>
    <p>
        <?php echo $this->tag->linkTo(array("turma/new", "Criar turma")) ?>
    </p>
</div>

<?php echo $this->getContent() ?>

<?php
    echo $this->tag->form(
        array(
            "turma/search",
            "autocomplete" => "off",
            "class" => "form-horizontal"
        )
    );
?>

<div class="form-group">
    <label for="fieldAlunocodMatricula" class="col-sm-2 control-label">Alunocod Of Matricula</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(array("alunocod_matricula", "type" => "number", "class" => "form-control", "id" => "fieldAlunocodMatricula")) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldProfesorpessoacodigo" class="col-sm-2 control-label">Profesorpessoacodigo</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(array("profesorpessoacodigo", "type" => "number", "class" => "form-control", "id" => "fieldProfesorpessoacodigo")) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldCodtur" class="col-sm-2 control-label">Codtur</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(array("codtur", "type" => "number", "class" => "form-control", "id" => "fieldCodtur")) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldDestur" class="col-sm-2 control-label">Destur</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(array("destur", "size" => 30, "class" => "form-control", "id" => "fieldDestur")) ?>
    </div>
</div>


<div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
        <?php echo $this->tag->submitButton(array("Pesquisar", "class" => "btn btn-default")) ?>
    </div>
</div>

<?php echo $this->tag->endForm(); ?>
