<?php
/**
 * @var \Phalcon\Mvc\View\Engine\Php $this
 */
?>

<?php use Phalcon\Tag; ?>

<div class="row">
    <nav>
        <ul class="pager">
            <li class="previous"><?php echo $this->tag->linkTo(array("turma/index", "Go Back")); ?></li>
            <li class="next"><?php echo $this->tag->linkTo(array("turma/new", "Create ")); ?></li>
        </ul>
    </nav>
</div>

<div class="page-header">
    <h1>Search result</h1>
</div>

<?php echo $this->getContent(); ?>

<div class="row">
    <table class="table table-bordered">
        <thead>
            <tr>
                <th>Alunocod Of Matricula</th>
            <th>Profesorpessoacodigo</th>
            <th>Codtur</th>
            <th>Destur</th>

                <th></th>
                <th></th>
            </tr>
        </thead>
        <tbody>
        <?php foreach ($page->items as $turma): ?>
            <tr>
                <td><?php echo $turma->alunocod_matricula ?></td>
            <td><?php echo $turma->profesorpessoacodigo ?></td>
            <td><?php echo $turma->codtur ?></td>
            <td><?php echo $turma->destur ?></td>

                <td><?php echo $this->tag->linkTo(array("turma/edit/" . $turma->alunocod_matricula, "Edit")); ?></td>
                <td><?php echo $this->tag->linkTo(array("turma/delete/" . $turma->alunocod_matricula, "Delete")); ?></td>
            </tr>
        <?php endforeach; ?>
        </tbody>
    </table>
</div>

<div class="row">
    <div class="col-sm-1">
        <p class="pagination" style="line-height: 1.42857;padding: 6px 12px;">
            <?php echo $page->current, "/", $page->total_pages ?>
        </p>
    </div>
    <div class="col-sm-11">
        <nav>
            <ul class="pagination">
                <li><?php echo $this->tag->linkTo("turma/search", "First") ?></li>
                <li><?php echo $this->tag->linkTo("turma/search?page=" . $page->before, "Previous") ?></li>
                <li><?php echo $this->tag->linkTo("turma/search?page=" . $page->next, "Next") ?></li>
                <li><?php echo $this->tag->linkTo("turma/search?page=" . $page->last, "Last") ?></li>
            </ul>
        </nav>
    </div>
</div>
