<?php
/**
 * @var \Phalcon\Mvc\View\Engine\Php $this
 */
?>

<div class="page-header">
    <h1>
        Curso
    </h1>
    <p>
        <?php echo $this->tag->linkTo(array("curso/new", "Criar curso")) ?>
    </p>
</div>

<?php echo $this->getContent() ?>

<?php
    echo $this->tag->form(
        array(
            "curso/search",
            "autocomplete" => "off",
            "class" => "form-horizontal"
        )
    );
?>

<div class="form-group">
    <label for="fieldCodcur" class="col-sm-2 control-label">Código: </label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(array("codcur", "type" => "number", "class" => "form-control", "id" => "fieldCodcur")) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldDescur" class="col-sm-2 control-label">Nome: </label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(array("descur", "type" => "number", "class" => "form-control", "id" => "fieldDescur")) ?>
    </div>
</div>


<div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
        <?php echo $this->tag->submitButton(array("Pesquisar", "class" => "btn btn-default")) ?>
    </div>
</div>

<?php echo $this->tag->endForm(); ?>
