<?php
/**
 * @var \Phalcon\Mvc\View\Engine\Php $this
 */
?>

<div class="row">
    <nav>
        <ul class="pager">
            <li class="previous"><?php echo $this->tag->linkTo(array("curso", "Voltar")) ?></li>
        </ul>
    </nav>
</div>

<div class="page-header">
    <h1>
        Cadastrar Curso
    </h1>
</div>

<?php echo $this->getContent(); ?>

<?php
    echo $this->tag->form(
        array(
            "curso/create",
            "autocomplete" => "off",
            "class" => "form-horizontal"
        )
    );
?>

<div class="form-group">
    <label for="fieldDescur" class="col-sm-2 control-label">Descrição do curso : </label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(array("descur", "type" => "number", "class" => "form-control", "id" => "fieldDescur")) ?>
    </div>
</div>


<div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
        <?php echo $this->tag->submitButton(array("Salvar", "class" => "btn btn-default")) ?>
    </div>
</div>

<?php echo $this->tag->endForm(); ?>
