<?php
/**
 * @var \Phalcon\Mvc\View\Engine\Php $this
 */
?>

<div class="page-header">
    <h1>
        Peer perguntas
    </h1>
    <p>
        <?php echo $this->tag->linkTo(array("peerperguntas/new", "Criar peer perguntas")) ?>
    </p>
</div>

<?php echo $this->getContent() ?>

<?php
    echo $this->tag->form(
        array(
            "peerperguntas/search",
            "autocomplete" => "off",
            "class" => "form-horizontal"
        )
    );
?>

<div class="form-group">
    <label for="fieldPerguntacodper" class="col-sm-2 control-label">Código da pergunta </label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(array("perguntacodper", "type" => "number", "class" => "form-control", "id" => "fieldPerguntacodper")) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldPeercodpee" class="col-sm-2 control-label">Código do peer </label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(array("peercodpee", "type" => "number", "class" => "form-control", "id" => "fieldPeercodpee")) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldOrdpee" class="col-sm-2 control-label">Ordem do peer </label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(array("ordpee", "type" => "number", "class" => "form-control", "id" => "fieldOrdpee")) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldObrirespeer" class="col-sm-2 control-label">Obrigatoriedade das pergutas </label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(array("obrirespeer", "type" => "number", "class" => "form-control", "id" => "fieldObrirespeer")) ?>
    </div>
</div>


<div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
        <?php echo $this->tag->submitButton(array("Pesquisar", "class" => "btn btn-default")) ?>
    </div>
</div>

<?php echo $this->tag->endForm(); ?>
