<?php
/**
 * @var \Phalcon\Mvc\View\Engine\Php $this
 */
?>

<div class="row">
    <nav>
        <ul class="pager">
            <li class="previous"><?php echo $this->tag->linkTo(array("peerperguntas", "Voltar")) ?></li>
        </ul>
    </nav>
</div>

<div class="page-header">
    <h1>
        Criar perguntas
    </h1>
</div>

<?php echo $this->getContent(); ?>

<?php
    echo $this->tag->form(
        array(
            "peerperguntas/create",
            "autocomplete" => "off",
            "class" => "form-horizontal"
        )
    );
?>

<div class="form-group">
    <label for="peerper" class="col-sm-2 control-label">Descrição do peer: </label>
    <div class="col-sm-10">
         <?php echo $this->tag->select(["peer", $peer, "using" => ["codpee","despee"]]) ?>
        
    </div>
</div>
<div class="form-group">
    <label for="peerper" class="col-sm-2 control-label">Descrição da pergunta: </label>
    <div class="col-sm-10">
        <?php echo $this->tag->textArea(array("peerper",  "class" => "form-control", "id" => "peerper" )) ?>
    </div>
</div>
<div class="form-group">
    <div class="col-sm-1">
        <?php echo $this->tag->radioField(array("rescerta",  "id" => "rescerta", "value" => 1)) ?>
    </div>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(array("resposta1", "type" => "text", "class" => "form-control", "id" => "resposta1")) ?>
    </div>        
</div>
<div class="form-group">
    <div class="col-sm-1">
        <?php echo $this->tag->radioField(array("rescerta",  "id" => "rescerta", "value" => 2)) ?>
    </div>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(array("resposta2", "type" => "text", "class" => "form-control", "id" => "resposta2")) ?>
    </div>        
</div>
 <div class="form-group">
    <div class="col-sm-1">
        <?php echo $this->tag->radioField(array("rescerta",  "id" => "rescerta", "value" => 3)) ?>
    </div>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(array("resposta3", "type" => "text", "class" => "form-control", "id" => "resposta3")) ?>
    </div>        
</div>
<div class="form-group">
    <div class="col-sm-1">
        <?php echo $this->tag->radioField(array("rescerta",  "id" => "rescerta", "value" => 4)) ?>
    </div>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(array("resposta4", "type" => "text", "class" => "form-control", "id" => "resposta4")) ?>
    </div>        
</div>

<div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
        <?php echo $this->tag->submitButton(array("Criar", "class" => "btn btn-default")) ?>
    </div>
</div>

<?php echo $this->tag->endForm(); ?>