<?php
/**
 * @var \Phalcon\Mvc\View\Engine\Php $this
 */
?>

<div class="page-header">
    <h1>
        Disciplina
    </h1>
    <p>
        <?php echo $this->tag->linkTo(array("disciplina/new", "Criar disciplina")) ?>
    </p>
</div>

<?php echo $this->getContent() ?>

<?php
    echo $this->tag->form(
        array(
            "disciplina/search",
            "autocomplete" => "off",
            "class" => "form-horizontal"
        )
    );
?>

<div class="form-group">
    <label for="fieldCodDis" class="col-sm-2 control-label">Código da disciplina </label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(array("cod_dis", "type" => "number", "class" => "form-control", "id" => "fieldCodDis")) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldDesdis" class="col-sm-2 control-label">Descrição da disciplina </label>
    <div class="col-sm-10">
        <?php echo $this->tag->textArea(array("desdis", "cols" => 30, "rows" => 4, "class" => "form-control", "id" => "fieldDesdis")) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldTurmacodtur" class="col-sm-2 control-label">Código da turma </label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(array("turmacodtur", "type" => "number", "class" => "form-control", "id" => "fieldTurmacodtur")) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldCarhordis" class="col-sm-2 control-label">Carga horaria disciplina </label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(array("carhordis", "type" => "number", "class" => "form-control", "id" => "fieldCarhordis")) ?>
    </div>
</div>


<div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
        <?php echo $this->tag->submitButton(array("Procurar", "class" => "btn btn-default")) ?>
    </div>
</div>

<?php echo $this->tag->endForm(); ?>
