<?php
/**
 * @var \Phalcon\Mvc\View\Engine\Php $this
 */
?>

<div class="row">
    <nav>
        <ul class="pager">
            <li class="previous"><?php echo $this->tag->linkTo(array("disciplina", "Voltar")) ?></li>
        </ul>
    </nav>
</div>

<div class="page-header">
    <h1>
        Criar disciplina
    </h1>
</div>

<?php echo $this->getContent(); ?>

<?php
    echo $this->tag->form(
        array(
            "disciplina/create",
            "autocomplete" => "off",
            "class" => "form-horizontal"
        )
    );
?>

<div class="form-group">
    <label for="fieldDesdis" class="col-sm-2 control-label">Nome: </label>
    <div class="col-sm-10">
        <?php echo $this->tag->textArea(array("desdis", "cols" => 30, "rows" => 4, "class" => "form-control", "id" => "fieldDesdis")) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldTurmacodtur" class="col-sm-2 control-label">Código:</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(array("turmacodtur", "type" => "number", "class" => "form-control", "id" => "fieldTurmacodtur")) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldCarhordis" class="col-sm-2 control-label">Carga horaria:</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(array("carhordis", "type" => "number", "class" => "form-control", "id" => "fieldCarhordis")) ?>
    </div>
</div>


<div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
        <?php echo $this->tag->submitButton(array("Salvar", "class" => "btn btn-default")) ?>
    </div>
</div>

<?php echo $this->tag->endForm(); ?>
