<?php
/**
 * @var \Phalcon\Mvc\View\Engine\Php $this
 */
?>

<?php use Phalcon\Tag; ?>

<div class="row">
    <nav>
        <ul class="pager">
            <li class="previous"><?php echo $this->tag->linkTo(array("disciplina/index", "Voltar")); ?></li>
            <li class="next"><?php echo $this->tag->linkTo(array("disciplina/new", "Criar ")); ?></li>
        </ul>
    </nav>
</div>

<div class="page-header">
    <h1>Pesquisar resultados</h1>
</div>

<?php echo $this->getContent(); ?>

<div class="row">
    <table class="table table-bordered">
        <thead>
            <tr>
                <th>Cod Of Dis</th>
            <th>Desdis</th>
            <th>Turmacodtur</th>
            <th>Carhordis</th>

                <th></th>
                <th></th>
            </tr>
        </thead>
        <tbody>
        <?php foreach ($page->items as $disciplina): ?>
            <tr>
                <td><?php echo $disciplina->cod_dis ?></td>
            <td><?php echo $disciplina->desdis ?></td>
            <td><?php echo $disciplina->turmacodtur ?></td>
            <td><?php echo $disciplina->carhordis ?></td>

                <td><?php echo $this->tag->linkTo(array("disciplina/edit/" . $disciplina->cod_dis, "Edit")); ?></td>
                <td><?php echo $this->tag->linkTo(array("disciplina/delete/" . $disciplina->cod_dis, "Delete")); ?></td>
            </tr>
        <?php endforeach; ?>
        </tbody>
    </table>
</div>

<div class="row">
    <div class="col-sm-1">
        <p class="pagination" style="line-height: 1.42857;padding: 6px 12px;">
            <?php echo $page->current, "/", $page->total_pages ?>
        </p>
    </div>
    <div class="col-sm-11">
        <nav>
            <ul class="pagination">
                <li><?php echo $this->tag->linkTo("disciplina/search", "First") ?></li>
                <li><?php echo $this->tag->linkTo("disciplina/search?page=" . $page->before, "Previous") ?></li>
                <li><?php echo $this->tag->linkTo("disciplina/search?page=" . $page->next, "Next") ?></li>
                <li><?php echo $this->tag->linkTo("disciplina/search?page=" . $page->last, "Last") ?></li>
            </ul>
        </nav>
    </div>
</div>
